[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.build]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn -b 0.0.0.0:5000 server:app"
